/*
Characters from Worm who show up in fics as POV chars, important side chars
or OTPs.  I tend to prefer singular first names and only fall back to cape
names with chars we don't get to know by name quite so much.  To be honest,
this line is pretty arbitrary.  But at the very least, the terrible trio,
the once and future undersiders and new wave all get this treatment.
*/
module.exports = {
  "Night Gaunt": "https://en.wikipedia.org/wiki/Nightgaunt",

// worm chars
  "Accord": "http://worm.wikia.com/wiki/Accord",
  "Aegis": "http://worm.wikia.com/wiki/Aegis",
  "Aisha Laborn": "http://worm.wikia.com/wiki/Imp",
  "Alabaster": "http://worm.wikia.com/wiki/Alabaster",
  "Alec": "http://worm.wikia.com/wiki/Regent",
  "Annette": "http://worm.wikia.com/wiki/Annette_Hebert",
  "Regent": "http://worm.wikia.com/wiki/Regent",
  "Amy Dallon": "http://worm.wikia.com/wiki/Panacea",
  "Amy": "http://worm.wikia.com/wiki/Panacea",
  "Andrew Richter": "http://worm.wikia.com/wiki/Andrew_Richter",
  "Armsmaster": "http://worm.wikia.com/wiki/Armsmaster",
  "Ash Beast": "http://worm.wikia.com/wiki/Ash_Beast",
  "Assault": "http://worm.wikia.com/wiki/Assault",
  "Bitch/Hellhound": "http://worm.wikia.com/wiki/Bitch",
  "Bitch": "http://worm.wikia.com/wiki/Bitch",
  "Bakuda": "http://worm.wikia.com/wiki/Bakuda",
  "Bohu": "http://worm.wikia.com/wiki/Bohu",
  "Brian Laborn": "http://worm.wikia.com/wiki/Grue",
  "Brian": "http://worm.wikia.com/wiki/Grue",
  "Grue": "http://worm.wikia.com/wiki/Grue",
  "Carol Dallon": "http://worm.wikia.com/wiki/Brandish",
  "Brandish": "http://worm.wikia.com/wiki/Brandish",
  "Carlos": "http://worm.wikia.com/wiki/Aegis",
  "Charlotte": "http://worm.wikia.com/wiki/Charlotte",
  "Cherie": "http://worm.wikia.com/wiki/Cherish",
  "Chris": "http://worm.wikia.com/wiki/Kid_Win",
  "Ciara": "http://worm.wikia.com/wiki/Glaistig_Uaine",
  "Clockblocker": "http://worm.wikia.com/wiki/Clockblocker",
  "Coil": "http://worm.wikia.com/wiki/Coil",
  "Thomas Calvert": "http://worm.wikia.com/wiki/Coil",
  "Crystal Pelham": "http://worm.wikia.com/wiki/Crystal_Pelham",
  "Colin Wallis": "http://worm.wikia.com/wiki/Armsmaster",
  "Contessa": "http://worm.wikia.com/wiki/Contessa",
  "Damsel of Distress": "http://worm.wikia.com/wiki/Damsel_of_Distress",
  "Danny Hebert": "http://worm.wikia.com/wiki/Danny_Hebert",
  "Danny H.": "http://worm.wikia.com/wiki/Danny_Hebert",
  "Danny": "http://worm.wikia.com/wiki/Danny_Hebert",
  "Dennis": "http://worm.wikia.com/wiki/Clockblocker",
  "Dean": "http://worm.wikia.com/wiki/Gallant",
  "Dean Stansfield": "http://worm.wikia.com/wiki/Gallant",
  "Dinah Alcott": "http://worm.wikia.com/wiki/Dinah",
  "Dinah": "http://worm.wikia.com/wiki/Dinah",
  "Doctor Mother": "http://worm.wikia.com/wiki/Doctor_Mother",
  "Dragon": "http://worm.wikia.com/wiki/Dragon",
  "Eidolon": "http://worm.wikia.com/wiki/Eidolon",
  "Emily Piggot": "http://worm.wikia.com/wiki/Emily_Piggot",
  "Elle": "http://worm.wikia.com/wiki/Labyrinth",
  "Emma Barnes": "http://worm.wikia.com/wiki/Emma_Barnes",
  "Emma B.": "http://worm.wikia.com/wiki/Emma_Barnes",
  "Emma": "http://worm.wikia.com/wiki/Emma_Barnes",
  "Eric Pelham": "http://worm.wikia.com/wiki/Shielder",
  "Faultline": "http://worm.wikia.com/wiki/Faultline",
  "Flechette": "http://worm.wikia.com/wiki/Flechette",
  "Gallant": "http://worm.wikia.com/wiki/Gallant",
  "Glaistig Uaine": "http://worm.wikia.com/wiki/Glaistig_Uaine",
  "Greg Veder": "http://worm.wikia.com/wiki/Greg_Veder",
  "Greg": "http://worm.wikia.com/wiki/Greg_Veder",
  "Hannah": "http://worm.wikia.com/wiki/Miss_Militia",
  "Jack Slash": "http://worm.wikia.com/wiki/Jack_Slash",
  "Jacob": "http://worm.wikia.com/wiki/Jack_Slash",
  "Jessica Yamada": "http://worm.wikia.com/wiki/Jessica_Yamada",
  "Kid Win": "http://worm.wikia.com/wiki/Kid_Win",
  "Krouse": "http://worm.wikia.com/wiki/Trickster",
  "Labyrinth": "http://worm.wikia.com/wiki/Labyrinth",
  "Leet": "http://worm.wikia.com/wiki/Leet",
  "Tattletale": "http://worm.wikia.com/wiki/Tattletale",
  "Lab Rat": "http://worm.wikia.com/wiki/Lab_Rat",
  "Lady Photon": "http://worm.wikia.com/wiki/Lady_Photon",
  "Lisa Wilbourn": "http://worm.wikia.com/wiki/Tattletale",
  "Lisa": "http://worm.wikia.com/wiki/Tattletale",
  "Madison Clements": "http://worm.wikia.com/wiki/Madison_Clements",
  "Madison C.": "http://worm.wikia.com/wiki/Madison_Clements",
  "Madison": "http://worm.wikia.com/wiki/Madison_Clements",
  "Mark Dallon": "http://worm.wikia.com/wiki/Mark_Dallon",
  "Marquis": "http://worm.wikia.com/wiki/Marquis",
  "Mazinger Z(ero)": "http://mazinger.wikia.com/wiki/Mazinger_Z_(ZERO)",
  "Burnscar": "http://worm.wikia.com/wiki/Burnscar",
  "Mimi": "http://worm.wikia.com/wiki/Burnscar",
  "Miss Militia": "http://worm.wikia.com/wiki/Miss_Militia",
  "Missy Biron": "http://worm.wikia.com/wiki/Vista",
  "Missy": "http://worm.wikia.com/wiki/Vista",
  "Neil Pelham": "http://worm.wikia.com/wiki/Manpower",
  "Night": "http://worm.wikia.com/wiki/Night",
  "Nilbog": "http://worm.wikia.com/wiki/Nilbog",
  "Noelle": "http://worm.wikia.com/wiki/Noelle_Meinhardt",
  "Number Man": "http://worm.wikia.com/wiki/The_Number_Man",
  "Panacea": "http://worm.wikia.com/wiki/Panacea",
  "Rachel Lindt": "http://worm.wikia.com/wiki/Bitch",
  "Rachel": "http://worm.wikia.com/wiki/Bitch",
  "Riley": "http://worm.wikia.com/wiki/Bonesaw",
  "Bonesaw": "http://worm.wikia.com/wiki/Bonesaw",
  "Rune": "http://worm.wikia.com/wiki/Rune",
  "Sabah": "http://worm.wikia.com/wiki/Parian",
  "Saint": "http://worm.wikia.com/wiki/Saint",
  "Sarah Pelham": "http://worm.wikia.com/wiki/Lady_Photon",
  "Shatterbird": "http://worm.wikia.com/wiki/Shatterbird",
  "Simurgh": "http://worm.wikia.com/wiki/The_Simurgh",
  "Skidmark": "http://worm.wikia.com/wiki/Skidmark",
  "Sophia Hess": "http://worm.wikia.com/wiki/Shadow_Stalker",
  "Sophia": "http://worm.wikia.com/wiki/Shadow_Stalker",
  "Shadow Stalker": "http://worm.wikia.com/wiki/Shadow_Stalker",
  "Squealer": "http://worm.wikia.com/wiki/Squealer",
  "String Theory": "http://worm.wikia.com/wiki/String_Theory",
  "Skitter": "http://worm.wikia.com/wiki/Taylor_Hebert",
  "Taylor Hebert": "http://worm.wikia.com/wiki/Taylor_Hebert",
  "Taylor": "http://worm.wikia.com/wiki/Taylor_Hebert",
  "Tecton": "http://worm.wikia.com/wiki/Tecton",
  "Theo Anders": "http://worm.wikia.com/wiki/Golem",
  "Theo": "http://worm.wikia.com/wiki/Golem",
  "Tohu": "http://worm.wikia.com/wiki/Tohu",
  "Über": "http://worm.wikia.com/wiki/%C3%9Cber",
  "Velocity": "http://worm.wikia.com/wiki/Velocity",
  "Victoria Dallon": "http://worm.wikia.com/wiki/Glory_Girl",
  "Victoria D.": "http://worm.wikia.com/wiki/Glory_Girl",
  "Victoria": "http://worm.wikia.com/wiki/Glory_Girl",
  "Glory Girl": "http://worm.wikia.com/wiki/Glory_Girl",
  "Vista": "http://worm.wikia.com/wiki/Vista",
  "Weld": "http://worm.wikia.com/wiki/Weld",

// xover chars
  "Luthor": "https://en.wikipedia.org/wiki/Lex_Luthor",
  "Marvel!Odin": "https://marvel.com/universe/Odin",
  "Raven Branwen": "http://rwby.wikia.com/wiki/Raven_Branwen",
  "Ruby Rose": "http://rwby.wikia.com/wiki/Ruby_Rose",
  "Yawgmoth": "http://mtg.gamepedia.com/Yawgmoth",
  "Cú Chulainn": "https://en.wikipedia.org/wiki/C%C3%BA_Chulainn",
  "Millenium Earl": "https://en.wikipedia.org/wiki/Millennium_Earl",
  "Milo Murphy": "http://milomurphyslaw.wikia.com/wiki/Milo_Murphy",
  "Sauron": "https://en.wikipedia.org/wiki/Sauron",
  "Shuggoth": "https://en.wikipedia.org/wiki/Shoggoth",
  "T1000": "http://terminator.wikia.com/wiki/T-1000",

  "OC": "http://tvtropes.org/pmwiki/pmwiki.php/Main/OriginalCharacter",
}
