/*
Characters from Worm who show up in fics as POV chars, important side chars
or OTPs.  I tend to prefer singular first names and only fall back to cape
names with chars we don't get to know by name quite so much.  To be honest,
this line is pretty arbitrary.  But at the very least, the terrible trio,
the once and future undersiders and new wave all get this treatment.
*/
module.exports = {
// worm chars
  "Aegis": "http://worm.wikia.com/wiki/Aegis",
  "Alec": "http://worm.wikia.com/wiki/Regent",
  "Amy": "http://worm.wikia.com/wiki/Panacea",
  "Armsmaster": "http://worm.wikia.com/wiki/Armsmaster",
  "Bohu": "http://worm.wikia.com/wiki/Bohu",
  "Cherie": "http://worm.wikia.com/wiki/Cherish",
  "Chris": "http://worm.wikia.com/wiki/Kid_Win",
  "Coil": "http://worm.wikia.com/wiki/Coil",
  "Contessa": "http://worm.wikia.com/wiki/Contessa",
  "Damsel of Distress": "http://worm.wikia.com/wiki/Damsel_of_Distress",
  "Danny": "http://worm.wikia.com/wiki/Danny_Hebert",
  "Dennis": "http://worm.wikia.com/wiki/Clockblocker",
  "Dinah": "http://worm.wikia.com/wiki/Dinah",
  "Dragon": "http://worm.wikia.com/wiki/Dragon",
  "Elle": "http://worm.wikia.com/wiki/Labyrinth",
  "Emma": "http://worm.wikia.com/wiki/Emma_Barnes",
  "Glaistig Uaine": "http://worm.wikia.com/wiki/Glaistig_Uaine",
  "Greg": "http://worm.wikia.com/wiki/Greg_Veder",
  "Jack Slash": "http://worm.wikia.com/wiki/Jack_Slash",
  "Jessica Yamada": "http://worm.wikia.com/wiki/Jessica_Yamada",
  "Krouse": "http://worm.wikia.com/wiki/Trickster",
  "Labyrinth": "http://worm.wikia.com/wiki/Labyrinth",
  "Leet": "http://worm.wikia.com/wiki/Leet",
  "Lisa": "http://worm.wikia.com/wiki/Tattletale",
  "Madison": "http://worm.wikia.com/wiki/Madison_Clements",
  "Mimi": "http://worm.wikia.com/wiki/Burnscar",
  "Missy": "http://worm.wikia.com/wiki/Vista",
  "Night": "http://worm.wikia.com/wiki/Night",
  "Noelle": "http://worm.wikia.com/wiki/Noelle_Meinhardt",
  "Number Man": "http://worm.wikia.com/wiki/The_Number_Man",
  "Rachel": "http://worm.wikia.com/wiki/Bitch",
  "Riley": "http://worm.wikia.com/wiki/Bonesaw",
  "Rune": "http://worm.wikia.com/wiki/Rune",
  "Sabah": "http://worm.wikia.com/wiki/Parian",
  "Saint": "http://worm.wikia.com/wiki/Saint",
  "Shatterbird": "http://worm.wikia.com/wiki/Shatterbird",
  "Simurgh": "http://worm.wikia.com/wiki/The_Simurgh",
  "Sophia Hess": "http://worm.wikia.com/wiki/Shadow_Stalker",
  "Sophia": "http://worm.wikia.com/wiki/Shadow_Stalker",
  "Taylor": "http://worm.wikia.com/wiki/Taylor_Hebert",
  "Tohu": "http://worm.wikia.com/wiki/Tohu",
  "Über": "http://worm.wikia.com/wiki/%C3%9Cber",
  "Velocity": "http://worm.wikia.com/wiki/Velocity",

// xover chars
  "Marvel!Odin": "https://marvel.com/universe/Odin",
  "Raven Branwen": "http://rwby.wikia.com/wiki/Raven_Branwen",
  "Ruby Rose": "http://rwby.wikia.com/wiki/Ruby_Rose",
  "Yawgmoth": "http://mtg.gamepedia.com/Yawgmoth",
  "Cú Chulainn": "https://en.wikipedia.org/wiki/C%C3%BA_Chulainn",
  "Millenium Earl": "https://en.wikipedia.org/wiki/Millennium_Earl",

  "OC": "http://tvtropes.org/pmwiki/pmwiki.php/Main/OriginalCharacter",
}
