/*
This is series that Worm fics may show up as a crossover or fusion with. 
These can also be used as sources for altpowers.
*/
module.exports = {
  "Bionicle": "https://en.wikipedia.org/wiki/Bionicle",
  "Blame!": "https://en.wikipedia.org/wiki/Blame!",
  "Bravely Default": "https://en.wikipedia.org/wiki/Bravely_Default",
  "Captain Marvel": "https://en.wikipedia.org/wiki/Captain_Marvel_(DC_Comics)",
  "Castlevania": "https://en.wikipedia.org/wiki/Castlevania",
  "Danny Phantom": "https://en.wikipedia.org/wiki/Danny_Phantom",
  "Dark Souls 2": "https://en.wikipedia.org/wiki/Dark_Souls_II",
  "Death Note": "https://en.wikipedia.org/wiki/Death_Note",
  "Diablo": "https://en.wikipedia.org/wiki/Diablo_(video_game)",
  "Disgaea": "https://en.wikipedia.org/wiki/Disgaea",
  "Doctor Who": "https://en.wikipedia.org/wiki/Doctor_Who",
  "Dollhouse": "https://en.wikipedia.org/wiki/Dollhouse_(TV_series)",
  "Dragon's Dogma": "https://en.wikipedia.org/wiki/Dragon%27s_Dogma",
  "Dresden Files": "https://en.wikipedia.org/wiki/The_Dresden_Files",
  "Fallout": "https://en.wikipedia.org/wiki/Fallout_(series)",
  "Final Fantasy Brave EXVIUS": "http://exvius.gamepedia.com/Final_Fantasy_Brave_Exvius_Wiki",
  "Final Fantasy XIV": "https://en.wikipedia.org/wiki/Final_Fantasy_XIV",
  "Gamer": "https://en.wikipedia.org/wiki/The_Gamer_(manhwa)",
  "Grey Goo": "https://en.wikipedia.org/wiki/Grey_Goo_(video_game)",
  "Guyver": "https://en.wikipedia.org/wiki/Bio_Booster_Armor_Guyver",
  "Heroes of the Storm": "https://en.wikipedia.org/wiki/Heroes_of_the_Storm",
  "Homestuck": "https://en.wikipedia.org/wiki/Homestuck",
  "Horizon Zero Dawn": "https://en.wikipedia.org/wiki/Horizon_Zero_Dawn",
  "Kancolle": "http://kancolle.wikia.com/wiki/Kancolle_Wiki",
  "Kantai Collection": "https://en.wikipedia.org/wiki/Kantai_Collection",
  "Kingdom Hearts": "https://en.wikipedia.org/wiki/Kingdom_Hearts",
  "Kirby": "https://en.wikipedia.org/wiki/Kirby_(series)",
  "Kill Six Billion Demons": "http://tvtropes.org/pmwiki/pmwiki.php/Webcomic/KillSixBillionDemons",
  "Leviathan": "http://worm.wikia.com/wiki/Leviathan",
  "Lord of the Rings": "https://en.wikipedia.org/wiki/The_Lord_of_the_Rings",
  "Luna Varga": "https://www.animenewsnetwork.com/encyclopedia/anime.php?id=553",
  "Magic: The Gathering": "https://en.wikipedia.org/wiki/Magic:_The_Gathering",
  "Magical Girl Lyrical Nanoha": "https://en.wikipedia.org/wiki/Magical_Girl_Lyrical_Nanoha",
  "Mass Effect": "https://en.wikipedia.org/wiki/Mass_Effect",
  "Minecraft": "https://en.wikipedia.org/wiki/Minecraft",
  "Monster Hunter": "https://en.wikipedia.org/wiki/Monster_Hunter",
  "Naruto": "https://en.wikipedia.org/wiki/Naruto",
  "One Piece": "https://en.wikipedia.org/wiki/One_Piece",
  "Overwatch": "https://en.wikipedia.org/wiki/Overwatch_(video_game)",
  "Persona": "https://en.wikipedia.org/wiki/Persona_(series)",
  "Polity": "https://en.wikipedia.org/wiki/Neal_Asher#Polity_universe",
  "Punisher": "https://en.wikipedia.org/wiki/Punisher",
  "RWBY": "https://en.wikipedia.org/wiki/RWBY",
  "Schlock Mercenary": "https://en.wikipedia.org/wiki/Schlock_Mercenary",
  "SCP-Wiki": "http://www.scp-wiki.net/",
  "Shin Megami Tensei": "https://en.wikipedia.org/wiki/Shin_Megami_Tensei",
  "Skyrim": "https://en.wikipedia.org/wiki/The_Elder_Scrolls_V:_Skyrim",
  "Spider-Man": "https://en.wikipedia.org/wiki/Spider-Man",
  "Star Wars": "https://en.wikipedia.org/wiki/Star_Wars",
  "The Culture": "https://en.wikipedia.org/wiki/The_Culture",
  "The Gamer": "https://en.wikipedia.org/wiki/The_Gamer_(manhwa)",
  "Undertale": "https://en.wikipedia.org/wiki/Undertale",
  "Vampire: The Requiem": "https://en.wikipedia.org/wiki/Vampire:_The_Requiem",
  "Warhammer 40k": "https://en.wikipedia.org/wiki/Warhammer_40,000",
  "Wheel of Time": "https://en.wikipedia.org/wiki/The_Wheel_of_Time",
  "Young Justice": "https://en.wikipedia.org/wiki/Young_Justice_(TV_series)",
}
