/*
This is series that Worm fics may show up as a crossover or fusion with. 
These can also be used as sources for altpowers.
*/
module.exports = {
  "Absolver": "https://en.wikipedia.org/wiki/Absolver",
  "Addams Family": "https://en.wikipedia.org/wiki/The_Addams_Family",
  "ADRPG": "https://en.wikipedia.org/wiki/Amber_Diceless_Roleplaying_Game",
  "Agent Carter": "https://en.wikipedia.org/wiki/Agent_Carter_(TV_series)",
  "Ajin": "https://en.wikipedia.org/wiki/Ajin:_Demi-Human",
  "All For the Game": "https://www.goodreads.com/series/105824-all-for-the-game",
  "American McGee's Alice": "https://en.wikipedia.org/wiki/American_McGee%27s_Alice",
  "Arpeggio of Blue Steel": "https://en.wikipedia.org/wiki/Arpeggio_of_Blue_Steel",
  "Asura's Wrath": "https://en.wikipedia.org/wiki/Asura%27s_Wrath",
  "Avatar: The Last Airbender": "https://en.wikipedia.org/wiki/Avatar:_The_Last_Airbender",
  "Avatar: Legend of Korra": "https://en.wikipedia.org/wiki/The_Legend_of_Korra",
  "Badass of the Week": "http://www.badassoftheweek.com/",
  "Batgirl": "https://en.wikipedia.org/wiki/Batgirl",
  "Battletech": "https://en.wikipedia.org/wiki/BattleTech",
  "Bayonetta": "https://en.wikipedia.org/wiki/Bayonetta",
  "Beast: the Primordial": "http://whitewolf.wikia.com/wiki/Beast:_The_Primordial",
  "Bendy and the Ink Machine": "https://en.wikipedia.org/wiki/Bendy_and_the_Ink_Machine",
  "Big Hero 6": "https://en.wikipedia.org/wiki/Big_Hero_6_(film)",
  "Bionicle": "https://en.wikipedia.org/wiki/Bionicle",
  "Blame!": "https://en.wikipedia.org/wiki/Blame!",
  "Bleach": "https://en.wikipedia.org/wiki/Bleach_(anime)",
  "Bloodborne": "https://en.wikipedia.org/wiki/Bloodborne",
  "Boku no Hero Academia": "https://en.wikipedia.org/wiki/My_Hero_Academia",
  "Bravely Default": "https://en.wikipedia.org/wiki/Bravely_Default",
  "Captain Marvel": "https://en.wikipedia.org/wiki/Captain_Marvel_(DC_Comics)",
  "Castlevania": "https://en.wikipedia.org/wiki/Castlevania",
  "Cataclysm: Dark Days Ahead": "https://en.wikipedia.org/wiki/Cataclysm:_Dark_Days_Ahead",
  "CnC Tiberium Saga": "https://en.wikipedia.org/wiki/Command_%26_Conquer:_Tiberian_series",
  "COD: Zombies": "https://www.callofduty.com/wwii/zombies",
  "Chronicle": "https://en.wikipedia.org/wiki/Chronicle_(film)",
  "Chronicles of Amber": "https://en.wikipedia.org/wiki/The_Chronicles_of_Amber",
  "The Culture": "https://en.wikipedia.org/wiki/The_Culture",
  "Cthulhutech": "https://en.wikipedia.org/wiki/CthulhuTech",
  "D.Gray-Man": "https://en.wikipedia.org/wiki/D.Gray-man",
  "D&D": "https://en.wikipedia.org/wiki/Dungeons_%26_Dragons",
  "d20": "https://en.wikipedia.org/wiki/D20_System",
  "Danny Phantom": "https://en.wikipedia.org/wiki/Danny_Phantom",
  "Daredevil": "https://en.wikipedia.org/wiki/Daredevil_(Marvel_Comics_character)",
  "Dark Souls 2": "https://en.wikipedia.org/wiki/Dark_Souls_II",
  "Dark Souls":  "https://en.wikipedia.org/wiki/Dark_Souls",
  "Darkest Dungeon": "https://en.wikipedia.org/wiki/Darkest_Dungeon",
  "Deadman Wonderland": "https://en.wikipedia.org/wiki/Deadman_Wonderland",
  "Death Note": "https://en.wikipedia.org/wiki/Death_Note",
  "Destiny": "https://en.wikipedia.org/wiki/Destiny_(video_game)",
  "DMC": "https://en.wikipedia.org/wiki/DmC:_Devil_May_Cry",
  "Devouring Stars": "http://store.steampowered.com/app/354230/Devouring_Stars/",
  "Diablo": "https://en.wikipedia.org/wiki/Diablo_(video_game)",
  "Digimon": "https://en.wikipedia.org/wiki/Digimon",
  "Disgaea": "https://en.wikipedia.org/wiki/Disgaea",
  "Dishonored": "https://en.wikipedia.org/wiki/Dishonored",
  "Doctor Who": "https://en.wikipedia.org/wiki/Doctor_Who",
  "Dollhouse": "https://en.wikipedia.org/wiki/Dollhouse_(TV_series)",
  "Dominions 4": "http://store.steampowered.com/app/259060/Dominions_4_Thrones_of_Ascension/",
  "DOOM": "https://en.wikipedia.org/wiki/Doom_(series)",
  "Dragon's Dogma": "https://en.wikipedia.org/wiki/Dragon%27s_Dogma",
  "Dragon Ball Z": "https://en.wikipedia.org/wiki/Dragon_Ball_Z",
  "Dragon Ball": "https://en.wikipedia.org/wiki/Dragon_Ball",
  "The Dresden Files": "https://en.wikipedia.org/wiki/The_Dresden_Files",
  "Dresden Files": "https://en.wikipedia.org/wiki/The_Dresden_Files",
  "Dungeon Keeper": "https://en.wikipedia.org/wiki/Dungeon_Keeper",
  "Dwarf Fortress": "https://en.wikipedia.org/wiki/Dwarf_Fortress",
  "Empire Builder": "https://en.wikipedia.org/wiki/Empire_Builder_(board_game)",
  "Endless Universe": "https://en.wikipedia.org/wiki/Endless_Space",
  "Evangelion": "https://en.wikipedia.org/wiki/Neon_Genesis_Evangelion",
  "EverQuest": "https://en.wikipedia.org/wiki/EverQuest",
  "Evolve": "https://en.wikipedia.org/wiki/Evolve_(video_game)",
  "Exalted": "https://en.wikipedia.org/wiki/Exalted",
  "Factorio": "https://en.wikipedia.org/wiki/Factorio",
  "Fallout New Vegas": "https://en.wikipedia.org/wiki/Fallout:_New_Vegas",
  "Fallout": "https://en.wikipedia.org/wiki/Fallout_(series)",
  "Familiar of Zero": "https://en.wikipedia.org/wiki/The_Familiar_of_Zero",
  "Fate/Extra": "https://en.wikipedia.org/wiki/Fate/Extra",
  "Fate/stay night: Unlimited Blade Works": "https://en.wikipedia.org/wiki/Fate/stay_night:_Unlimited_Blade_Works",
  "Fate/stay night": "https://en.wikipedia.org/wiki/Fate/stay_night",
  "Fate/Grand Order": "http://fategrandorder.wikia.com/wiki/Fate/Grand_Order_Wikia",
  "Faultline": "http://worm.wikia.com/wiki/Faultline",
  "F.E.A.R": "https://en.wikipedia.org/wiki/F.E.A.R.",
  "FFTactics Advance": "https://en.wikipedia.org/wiki/Final_Fantasy_Tactics_Advance",
  "Final Fantasy Brave EXVIUS": "http://exvius.gamepedia.com/Final_Fantasy_Brave_Exvius_Wiki",
  "Final Fantasy XIV": "https://en.wikipedia.org/wiki/Final_Fantasy_XIV",
  "Final Fantasy": "https://en.wikipedia.org/wiki/Final_Fantasy",
  "FNAF:Pizzeria Simulator": "http://store.steampowered.com/app/738060/Freddy_Fazbears_Pizzeria_Simulator/",
  "FNaF": "https://en.wikipedia.org/wiki/Five_Nights_at_Freddy%27s",
  "Frozen": "https://en.wikipedia.org/wiki/Frozen_(2013_film)",
  "Full Metal Alchemist": "https://en.wikipedia.org/wiki/Fullmetal_Alchemist",
  "The Gamer": "https://en.wikipedia.org/wiki/The_Gamer_(manhwa)",
  "Gamer": "https://en.wikipedia.org/wiki/The_Gamer_(manhwa)",
  "Gamer": "https://en.wikipedia.org/wiki/The_Gamer_(manhwa)",
  "Garo": "https://en.wikipedia.org/wiki/Garo_(TV_series)",
  "Gate - Jietai Kare no Chi nite": "https://en.wikipedia.org/wiki/Gate_(novel_series)",
  "Generator Gawl": "https://en.wikipedia.org/wiki/Generator_Gawl",
  "Ghostbusters": "https://en.wikipedia.org/wiki/Ghostbusters_(franchise)",
  "Girl Genius": "https://en.wikipedia.org/wiki/Girl_Genius",
  "GitS": "https://en.wikipedia.org/wiki/Ghost_in_the_Shell",
  "God Eater Rage Burst": "https://en.wikipedia.org/wiki/God_Eater_2",
  "Gone": "https://en.wikipedia.org/wiki/Gone_(novel_series)",
  "Gravity Falls": "https://en.wikipedia.org/wiki/Gravity_Falls",
  "Gravity Rush": "https://en.wikipedia.org/wiki/Gravity_Rush",
  "Grey Goo": "https://en.wikipedia.org/wiki/Grey_Goo_(video_game)",
  "Grim Dawn": "https://en.wikipedia.org/wiki/Grim_Dawn",
  "Guild Wars 2": "https://en.wikipedia.org/wiki/Guild_Wars_2",
  "Gundam": "https://en.wikipedia.org/wiki/Gundam",
  "Guyver": "https://en.wikipedia.org/wiki/Bio_Booster_Armor_Guyver",
  "Halo": "https://en.wikipedia.org/wiki/Halo_(series)",
  "Harry Potter": "https://en.wikipedia.org/wiki/Harry_Potter",
  "HellBlazer": "https://en.wikipedia.org/wiki/Hellblazer",
  "Hellsing Ultimate": "https://en.wikipedia.org/wiki/Hellsing",
  "Heroes of the Storm": "https://en.wikipedia.org/wiki/Heroes_of_the_Storm",
  "Heroic Age": "https://en.wikipedia.org/wiki/Heroic_Age_(anime)",
  "Hetalia: Axis Powers": "https://en.wikipedia.org/wiki/Hetalia:_Axis_Powers",
  "High School DxD": "https://en.wikipedia.org/wiki/High_School_DxD",
  "Highlander": "https://en.wikipedia.org/wiki/Highlander_(franchise)",
  "HISHE Villain Pub": "http://hishe.wikia.com/wiki/Villains_Pub",
  "Homestuck": "https://en.wikipedia.org/wiki/Homestuck",
  "Horizon Zero Dawn": "https://en.wikipedia.org/wiki/Horizon_Zero_Dawn",
  "Hotline Miami": "https://en.wikipedia.org/wiki/Hotline_Miami",
  "Incredibles": "https://en.wikipedia.org/wiki/The_Incredibles",
  "Infamous": "https://en.wikipedia.org/wiki/Infamous_(video_game)",
  "Infinity Blade": "https://en.wikipedia.org/wiki/Infinity_Blade",
  "Injustice": "https://en.wikipedia.org/wiki/Injustice:_Gods_Among_Us",
  "The Iron Giant": "https://en.wikipedia.org/wiki/The_Iron_Giant",
  "The Irregular at Magic High School": "https://en.wikipedia.org/wiki/The_Irregular_at_Magic_High_School",
  "iZombie": "https://en.wikipedia.org/wiki/IZombie_(TV_series)",
  "John Wick": "https://en.wikipedia.org/wiki/John_Wick",
  "Jojo's Bizarre Adventure": "https://en.wikipedia.org/wiki/JoJo%27s_Bizarre_Adventure",
  "JoJo's Bizarre Adventure": "https://en.wikipedia.org/wiki/JoJo%27s_Bizarre_Adventure",
  "Journey to the West/西遊記": "https://en.wikipedia.org/wiki/Journey_to_the_West",
  "Jumpchain": "https://www.reddit.com/r/JumpChain/",
  "Jurassic World": "https://en.wikipedia.org/wiki/Jurassic_World",
  "Kancolle": "http://kancolle.wikia.com/wiki/Kancolle_Wiki",
  "Kantai Collection": "https://en.wikipedia.org/wiki/Kantai_Collection",
  "Karas": "https://en.wikipedia.org/wiki/Karas_(anime)",
  "KHR": "https://en.wikipedia.org/wiki/Reborn!",
  "Kill la Kill": "https://en.wikipedia.org/wiki/Kill_la_Kill",
  "Kill Six Billion Demons": "http://tvtropes.org/pmwiki/pmwiki.php/Webcomic/KillSixBillionDemons",
  "The King of Braves GaoGaiGar": "https://en.wikipedia.org/wiki/The_King_of_Braves_GaoGaiGar",
  "Kingdom Hearts": "https://en.wikipedia.org/wiki/Kingdom_Hearts",
  "Kill La Kill": "https://en.wikipedia.org/wiki/Kill_la_Kill",
  "Kirby": "https://en.wikipedia.org/wiki/Kirby_(series)",
  "Ladybug and Cat Noir": "https://en.wikipedia.org/wiki/Miraculous:_Tales_of_Ladybug_%26_Cat_Noir",
  "League of Legends": "https://en.wikipedia.org/wiki/League_of_Legends",
  "Legend of Zelda": "https://en.wikipedia.org/wiki/The_Legend_of_Zelda",
  "BotW": "https://en.wikipedia.org/wiki/The_Legend_of_Zelda:_Breath_of_the_Wild",
  "Leviathan": "http://worm.wikia.com/wiki/Leviathan",
  "Life Is Strange": "https://en.wikipedia.org/wiki/Life_Is_Strange",
  "Lord of the Rings": "https://en.wikipedia.org/wiki/The_Lord_of_the_Rings",
  "Luna Varga": "https://www.animenewsnetwork.com/encyclopedia/anime.php?id=553",
  "Mage: the Ascension": "https://en.wikipedia.org/wiki/Mage:_The_Ascension",
  "Magic: The Gathering": "https://en.wikipedia.org/wiki/Magic:_The_Gathering",
  "Magical Girl Lyrical Nanoha": "https://en.wikipedia.org/wiki/Magical_Girl_Lyrical_Nanoha",
  "Mass Effect": "https://en.wikipedia.org/wiki/Mass_Effect",
  "Mazinger Z(ero)": "http://tvtropes.org/pmwiki/pmwiki.php/Manga/ShinMazingerZero",
  "MCU": "https://en.wikipedia.org/wiki/Marvel_Cinematic_Universe",
  "Medaka Box": "https://en.wikipedia.org/wiki/Medaka_Box",
  "Megaman": "https://en.wikipedia.org/wiki/Mega_Man",
  "MGRP": "https://en.wikipedia.org/wiki/Magical_Girl_Raising_Project",
  "MGS": "https://en.wikipedia.org/wiki/Metal_Gear_Solid",
  "Milo Murphy's Law": "https://en.wikipedia.org/wiki/Milo_Murphy%27s_Law",
  "Mind Dimensions": "https://www.goodreads.com/series/141102-mind-dimensions",
  "Minecraft": "https://en.wikipedia.org/wiki/Minecraft",
  "Miraculous Ladybug": "https://en.wikipedia.org/wiki/Miraculous:_Tales_of_Ladybug_%26_Cat_Noir",
  "Mistborn": "https://en.wikipedia.org/wiki/Mistborn_series",
  "MLP:FiM": "https://en.wikipedia.org/wiki/My_Little_Pony:_Friendship_Is_Magic",
  "Mononoke": "https://en.wikipedia.org/wiki/Princess_Mononoke",
  "Monster Girl Encyclopedia": "http://monstergirlencyclopedia.wikia.com/wiki/Monster_Girl_Encyclopedia",
  "Monster Hunter": "https://en.wikipedia.org/wiki/Monster_Hunter",
  "Morrowind": "https://en.wikipedia.org/wiki/The_Elder_Scrolls_III:_Morrowind",
  "Mummy: the Resurrection": "https://en.wikipedia.org/wiki/Mummy:_The_Resurrection",
  "Mushishi": "https://en.wikipedia.org/wiki/Mushishi",
  "Mutants and Masterminds": "https://en.wikipedia.org/wiki/Mutants_%26_Masterminds",
  "My Hero Academia": "https://en.wikipedia.org/wiki/My_Hero_Academia",
  "My Little Pony": "https://en.wikipedia.org/wiki/My_Little_Pony",
  "Naruto": "https://en.wikipedia.org/wiki/Naruto",
  "New World of Darkness": "https://en.wikipedia.org/wiki/World_of_Darkness#Chronicles_of_Darkness_.28formerly_New_World_of_Darkness.29",
  "Nobilis": "https://en.wikipedia.org/wiki/Nobilis",
  "Okami": "https://en.wikipedia.org/wiki/%C5%8Ckami",
  "One Piece": "https://en.wikipedia.org/wiki/One_Piece",
  "One Punch Man": "https://en.wikipedia.org/wiki/One-Punch_Man",
  "OneShot": "http://tvtropes.org/pmwiki/pmwiki.php/VideoGame/Oneshot",
  "Overlord": "https://en.wikipedia.org/wiki/Overlord_(novel_series)",
  "Overwatch": "https://en.wikipedia.org/wiki/Overwatch_(video_game)",
  "Patapon": "https://en.wikipedia.org/wiki/Patapon",
  "Pathfinder": "https://en.wikipedia.org/wiki/Pathfinder_Roleplaying_Game",
  "Persona": "https://en.wikipedia.org/wiki/Persona_(series)",
  "Poison Ivy": "https://en.wikipedia.org/wiki/Poison_Ivy_(character)",
  "Pokémon": "https://en.wikipedia.org/wiki/Pok%C3%A9mon",
  "Pokemon": "https://en.wikipedia.org/wiki/Pok%C3%A9mon",
  "Polity": "https://en.wikipedia.org/wiki/Neal_Asher#Polity_universe",
  "Problem Slueth": "http://tvtropes.org/pmwiki/pmwiki.php/Webcomic/ProblemSleuth",
  "Puella Magi Madoka Magica": "https://forums.spacebattles.com/threads/puella-magica-nicola-worm-pmm-oc.530185/",
  "Madoka Magica": "https://forums.spacebattles.com/threads/puella-magica-nicola-worm-pmm-oc.530185/",
  "Punisher": "https://en.wikipedia.org/wiki/Punisher",
  "Rise of the Guardians": "https://en.wikipedia.org/wiki/Rise_of_the_Guardians",
  "RWBY": "https://en.wikipedia.org/wiki/RWBY",
  "Rune": "http://worm.wikia.com/wiki/Rune",
  "Rurouni Kenshin": "https://en.wikipedia.org/wiki/Rurouni_Kenshin",
  "Sailor Moon": "https://en.wikipedia.org/wiki/Sailor_Moon",
  "Saints Row": "https://en.wikipedia.org/wiki/Saints_Row",
  "SBY 2199": "https://en.wikipedia.org/wiki/Space_Battleship_Yamato_2199",
  "Schlock Mercenary": "https://en.wikipedia.org/wiki/Schlock_Mercenary",
  "SCP-Wiki": "http://www.scp-wiki.net/",
  "SCP Foundation": "http://www.scp-wiki.net/",
  "The Secret World": "https://en.wikipedia.org/wiki/The_Secret_World",
  "Shin Megami Tensei": "https://en.wikipedia.org/wiki/Shin_Megami_Tensei",
  "Skies of Arcadia": "https://en.wikipedia.org/wiki/Skies_of_Arcadia",
  "Skyrim": "https://en.wikipedia.org/wiki/The_Elder_Scrolls_V:_Skyrim",
  "Slender Man": "http://creepypasta.wikia.com/wiki/The_Slender_Man",
  "Smallville": "https://en.wikipedia.org/wiki/Smallville",
  "SMITE": "https://en.wikipedia.org/wiki/Smite_(video_game)",
  "A Song of Ice and Fire": "https://en.wikipedia.org/wiki/A_Song_of_Ice_and_Fire",
  "Spider-Man": "https://en.wikipedia.org/wiki/Spider-Man",
  "The Stanley Parable": "https://en.wikipedia.org/wiki/The_Stanley_Parable",
  "Star Wars": "https://en.wikipedia.org/wiki/Star_Wars",
  "StarCraft": "https://en.wikipedia.org/wiki/StarCraft",
  "Stargate: SG-1": "https://en.wikipedia.org/wiki/Stargate_SG-1",
  "Steven Universe": "https://en.wikipedia.org/wiki/Steven_Universe",
  "Stormlight Archive": "https://en.wikipedia.org/wiki/The_Stormlight_Archive",
  "Stranger than Fiction": "https://en.wikipedia.org/wiki/Stranger_than_Fiction_(2006_film)",
  "Strong Female Protagonist": "https://strongfemaleprotagonist.com/",
  "The Suffering Game": "http://theadventurezone.wikia.com/wiki/Story_6:_The_Suffering_Game",
  "Super Robot Wars V": "https://en.wikipedia.org/wiki/Super_Robot_Wars_V",
  "Supergirl": "https://en.wikipedia.org/wiki/Supergirl",
  "Supernatural": "https://en.wikipedia.org/wiki/Supernatural_(U.S._TV_series)",
  "Suicide Squad": "https://en.wikipedia.org/wiki/Suicide_Squad_(film)",
  "Superman: Secret Identity": "https://en.wikipedia.org/wiki/Superman:_Secret_Identity",
  "Supreme Commander": "https://en.wikipedia.org/wiki/Supreme_Commander_(video_game)",
  "Sword Art Online": "https://en.wikipedia.org/wiki/Sword_Art_Online",
  "System Shock 2": "https://en.wikipedia.org/wiki/System_Shock_2",
  "Tengen Toppa Gurren Lagann": "https://en.wikipedia.org/wiki/Gurren_Lagann",
  "TES": "https://en.wikipedia.org/wiki/The_Elder_Scrolls",
  "The Elder Scrolls": "https://en.wikipedia.org/wiki/The_Elder_Scrolls",
  "The Garden of Sinners": "https://en.wikipedia.org/wiki/Kara_no_Ky%C5%8Dkai",
  "The Hulk": "https://en.wikipedia.org/wiki/Hulk_(comics)",
  "Tokyo Ghoul": "https://en.wikipedia.org/wiki/Tokyo_Ghoul",
  "Touhou": "https://en.wikipedia.org/wiki/Touhou_Project",
  "Thor": "https://en.wikipedia.org/wiki/Thor_(film)",
  "Transformers": "https://en.wikipedia.org/wiki/Transformers",
  "Type-Moon": "https://en.wikipedia.org/wiki/Type-Moon",
  "Undertale": "https://en.wikipedia.org/wiki/Undertale",
  "Vampire: The Requiem": "https://en.wikipedia.org/wiki/Vampire:_The_Requiem",
  "Ward": "http://www.parahumans.net/",
  "Warcraft": "https://en.wikipedia.org/wiki/Warcraft",
  "Warframe": "https://en.wikipedia.org/wiki/Warframe",
  "Warhammer 40k": "https://en.wikipedia.org/wiki/Warhammer_40,000",
  "40k": "https://en.wikipedia.org/wiki/Warhammer_40,000",
  "Warhammer 30k": "https://www.frontlinegaming.org/2015/11/13/the-horus-heresy-and-you-the-beginners-guide/",
  "Wheel of Time": "https://en.wikipedia.org/wiki/The_Wheel_of_Time",
  "Witcher": "https://en.wikipedia.org/wiki/The_Witcher",
  "Wonder Woman": "https://en.wikipedia.org/wiki/Wonder_Woman",
  "The World Ends With You": "https://en.wikipedia.org/wiki/The_World_Ends_with_You",
  "XCOM": "https://en.wikipedia.org/wiki/X-COM",
  "XCom": "https://en.wikipedia.org/wiki/X-COM",
  "X-Men": "https://en.wikipedia.org/wiki/X-Men",
  "TWEWY": "https://en.wikipedia.org/wiki/The_World_Ends_with_You",
  "Young Justice": "https://en.wikipedia.org/wiki/Young_Justice_(TV_series)",
  "Yugioh": "https://en.wikipedia.org/wiki/Yu-Gi-Oh!",
  "YuGiOh": "https://en.wikipedia.org/wiki/Yu-Gi-Oh!",
  "Yu-Gi-Oh": "https://en.wikipedia.org/wiki/Yu-Gi-Oh!",
}
