/*
This is series that Worm fics may show up as a crossover or fusion with. 
These can also be used as sources for altpowers.
*/
module.exports = {
  "All For the Game": "https://www.goodreads.com/series/105824-all-for-the-game",
  "American McGee's Alice": "https://en.wikipedia.org/wiki/American_McGee%27s_Alice",
  "Arpeggio of Blue Steel": "https://en.wikipedia.org/wiki/Arpeggio_of_Blue_Steel",
  "Big Hero 6": "https://en.wikipedia.org/wiki/Big_Hero_6_(film)",
  "Bionicle": "https://en.wikipedia.org/wiki/Bionicle",
  "Blame!": "https://en.wikipedia.org/wiki/Blame!",
  "Boku no Hero Academia": "https://en.wikipedia.org/wiki/My_Hero_Academia",
  "Bravely Default": "https://en.wikipedia.org/wiki/Bravely_Default",
  "Captain Marvel": "https://en.wikipedia.org/wiki/Captain_Marvel_(DC_Comics)",
  "Castlevania": "https://en.wikipedia.org/wiki/Castlevania",
  "Cataclysm: Dark Days Ahead": "https://en.wikipedia.org/wiki/Cataclysm:_Dark_Days_Ahead",
  "Chronicle": "https://en.wikipedia.org/wiki/Chronicle_(film)",
  "The Culture": "https://en.wikipedia.org/wiki/The_Culture",
  "D.Gray-Man": "https://en.wikipedia.org/wiki/D.Gray-man",
  "D&D": "https://en.wikipedia.org/wiki/Dungeons_%26_Dragons",
  "d20": "https://en.wikipedia.org/wiki/D20_System",
  "Danny Phantom": "https://en.wikipedia.org/wiki/Danny_Phantom",
  "Daredevil": "https://en.wikipedia.org/wiki/Daredevil_(Marvel_Comics_character)",
  "Dark Souls 2": "https://en.wikipedia.org/wiki/Dark_Souls_II",
  "Dark Souls":  "https://en.wikipedia.org/wiki/Dark_Souls",
  "Darkest Dungeon": "https://en.wikipedia.org/wiki/Darkest_Dungeon",
  "Deadman Wonderland": "https://en.wikipedia.org/wiki/Deadman_Wonderland",
  "Death Note": "https://en.wikipedia.org/wiki/Death_Note",
  "Destiny": "https://en.wikipedia.org/wiki/Destiny_(video_game)",
  "Diablo": "https://en.wikipedia.org/wiki/Diablo_(video_game)",
  "Digimon": "https://en.wikipedia.org/wiki/Digimon",
  "Disgaea": "https://en.wikipedia.org/wiki/Disgaea",
  "Dishonored": "https://en.wikipedia.org/wiki/Dishonored",
  "Doctor Who": "https://en.wikipedia.org/wiki/Doctor_Who",
  "Dollhouse": "https://en.wikipedia.org/wiki/Dollhouse_(TV_series)",
  "Dominions 4": "http://store.steampowered.com/app/259060/Dominions_4_Thrones_of_Ascension/",
  "DOOM": "https://en.wikipedia.org/wiki/Doom_(series)",
  "Dragon's Dogma": "https://en.wikipedia.org/wiki/Dragon%27s_Dogma",
  "Dragon Ball": "https://en.wikipedia.org/wiki/Dragon_Ball",
  "Dresden Files": "https://en.wikipedia.org/wiki/The_Dresden_Files",
  "Dungeon Keeper": "https://en.wikipedia.org/wiki/Dungeon_Keeper",
  "Evangelion": "https://en.wikipedia.org/wiki/Neon_Genesis_Evangelion",
  "Evolve": "https://en.wikipedia.org/wiki/Evolve_(video_game)",
  "Factorio": "https://en.wikipedia.org/wiki/Factorio",
  "Fallout": "https://en.wikipedia.org/wiki/Fallout_(series)",
  "Fate/Extra": "https://en.wikipedia.org/wiki/Fate/Extra",
  "Fate/stay night: Unlimited Blade Works": "https://en.wikipedia.org/wiki/Fate/stay_night:_Unlimited_Blade_Works",
  "Fate/stay night": "https://en.wikipedia.org/wiki/Fate/stay_night",
  "Final Fantasy Brave EXVIUS": "http://exvius.gamepedia.com/Final_Fantasy_Brave_Exvius_Wiki",
  "Final Fantasy XIV": "https://en.wikipedia.org/wiki/Final_Fantasy_XIV",
  "Final Fantasy": "https://en.wikipedia.org/wiki/Final_Fantasy",
  "Frozen": "https://en.wikipedia.org/wiki/Frozen_(2013_film)",
  "Full Metal Alchemist": "https://en.wikipedia.org/wiki/Fullmetal_Alchemist",
  "The Gamer": "https://en.wikipedia.org/wiki/The_Gamer_(manhwa)",
  "Gamer": "https://en.wikipedia.org/wiki/The_Gamer_(manhwa)",
  "Garo": "https://en.wikipedia.org/wiki/Garo_(TV_series)",
  "Ghostbusters": "https://en.wikipedia.org/wiki/Ghostbusters_(franchise)",
  "Gravity Falls": "https://en.wikipedia.org/wiki/Gravity_Falls",
  "Grey Goo": "https://en.wikipedia.org/wiki/Grey_Goo_(video_game)",
  "Guild Wars 2": "https://en.wikipedia.org/wiki/Guild_Wars_2",
  "Gundam": "https://en.wikipedia.org/wiki/Gundam",
  "Guyver": "https://en.wikipedia.org/wiki/Bio_Booster_Armor_Guyver",
  "Halo": "https://en.wikipedia.org/wiki/Halo_(series)",
  "Harry Potter": "https://en.wikipedia.org/wiki/Harry_Potter",
  "Hellsing Ultimate": "https://en.wikipedia.org/wiki/Hellsing",
  "Heroes of the Storm": "https://en.wikipedia.org/wiki/Heroes_of_the_Storm",
  "Hetalia: Axis Powers": "https://en.wikipedia.org/wiki/Hetalia:_Axis_Powers",
  "Homestuck": "https://en.wikipedia.org/wiki/Homestuck",
  "Horizon Zero Dawn": "https://en.wikipedia.org/wiki/Horizon_Zero_Dawn",
  "Hotline Miami": "https://en.wikipedia.org/wiki/Hotline_Miami",
  "Infamous": "https://en.wikipedia.org/wiki/Infamous_(video_game)",
  "Infinity Blade": "https://en.wikipedia.org/wiki/Infinity_Blade",
  "Injustice": "https://en.wikipedia.org/wiki/Injustice:_Gods_Among_Us",
  "The Iron Giant": "https://en.wikipedia.org/wiki/The_Iron_Giant",
  "The Irregular at Magic High School": "https://en.wikipedia.org/wiki/The_Irregular_at_Magic_High_School",
  "iZombie": "https://en.wikipedia.org/wiki/IZombie_(TV_series)",
  "Jojo's Bizarre Adventure": "https://en.wikipedia.org/wiki/JoJo%27s_Bizarre_Adventure",
  "Jurassic World": "https://en.wikipedia.org/wiki/Jurassic_World",
  "Kancolle": "http://kancolle.wikia.com/wiki/Kancolle_Wiki",
  "Kantai Collection": "https://en.wikipedia.org/wiki/Kantai_Collection",
  "Karas": "https://en.wikipedia.org/wiki/Karas_(anime)",
  "Kill Six Billion Demons": "http://tvtropes.org/pmwiki/pmwiki.php/Webcomic/KillSixBillionDemons",
  "The King of Braves GaoGaiGar": "https://en.wikipedia.org/wiki/The_King_of_Braves_GaoGaiGar",
  "Kingdom Hearts": "https://en.wikipedia.org/wiki/Kingdom_Hearts",
  "Kirby": "https://en.wikipedia.org/wiki/Kirby_(series)",
  "League of Legends": "https://en.wikipedia.org/wiki/League_of_Legends",
  "Leviathan": "http://worm.wikia.com/wiki/Leviathan",
  "Lord of the Rings": "https://en.wikipedia.org/wiki/The_Lord_of_the_Rings",
  "Luna Varga": "https://www.animenewsnetwork.com/encyclopedia/anime.php?id=553",
  "Mage: the Ascension": "https://en.wikipedia.org/wiki/Mage:_The_Ascension",
  "Magic: The Gathering": "https://en.wikipedia.org/wiki/Magic:_The_Gathering",
  "Magical Girl Lyrical Nanoha": "https://en.wikipedia.org/wiki/Magical_Girl_Lyrical_Nanoha",
  "Mass Effect": "https://en.wikipedia.org/wiki/Mass_Effect",
  "MCU": "https://en.wikipedia.org/wiki/Marvel_Cinematic_Universe",
  "Medaka Box": "https://en.wikipedia.org/wiki/Medaka_Box",
  "Megaman": "https://en.wikipedia.org/wiki/Mega_Man",
  "Minecraft": "https://en.wikipedia.org/wiki/Minecraft",
  "MLP:FiM": "https://en.wikipedia.org/wiki/My_Little_Pony:_Friendship_Is_Magic",
  "Mononoke": "https://en.wikipedia.org/wiki/Princess_Mononoke",
  "Monster Hunter": "https://en.wikipedia.org/wiki/Monster_Hunter",
  "Morrowind": "https://en.wikipedia.org/wiki/The_Elder_Scrolls_III:_Morrowind",
  "Mutants and Masterminds": "https://en.wikipedia.org/wiki/Mutants_%26_Masterminds",
  "Naruto": "https://en.wikipedia.org/wiki/Naruto",
  "Okami": "https://en.wikipedia.org/wiki/%C5%8Ckami",
  "One Piece": "https://en.wikipedia.org/wiki/One_Piece",
  "OneShot": "http://tvtropes.org/pmwiki/pmwiki.php/VideoGame/Oneshot",
  "Overwatch": "https://en.wikipedia.org/wiki/Overwatch_(video_game)",
  "Pathfinder": "https://en.wikipedia.org/wiki/Pathfinder_Roleplaying_Game",
  "Persona": "https://en.wikipedia.org/wiki/Persona_(series)",
  "Pokemon": "https://en.wikipedia.org/wiki/Pok%C3%A9mon",
  "Polity": "https://en.wikipedia.org/wiki/Neal_Asher#Polity_universe",
  "Puella Magi Madoka Magica": "https://forums.spacebattles.com/threads/puella-magica-nicola-worm-pmm-oc.530185/",
  "Punisher": "https://en.wikipedia.org/wiki/Punisher",
  "Rise of the Guardians": "https://en.wikipedia.org/wiki/Rise_of_the_Guardians",
  "RWBY": "https://en.wikipedia.org/wiki/RWBY",
  "Rune": "http://worm.wikia.com/wiki/Rune",
  "Sailor Moon": "https://en.wikipedia.org/wiki/Sailor_Moon",
  "Saints Row": "https://en.wikipedia.org/wiki/Saints_Row",
  "Schlock Mercenary": "https://en.wikipedia.org/wiki/Schlock_Mercenary",
  "SCP-Wiki": "http://www.scp-wiki.net/",
  "Shin Megami Tensei": "https://en.wikipedia.org/wiki/Shin_Megami_Tensei",
  "Skyrim": "https://en.wikipedia.org/wiki/The_Elder_Scrolls_V:_Skyrim",
  "Smallville": "https://en.wikipedia.org/wiki/Smallville",
  "SMITE": "https://en.wikipedia.org/wiki/Smite_(video_game)",
  "A Song of Ice and Fire": "https://en.wikipedia.org/wiki/A_Song_of_Ice_and_Fire",
  "Spider-Man": "https://en.wikipedia.org/wiki/Spider-Man",
  "The Stanley Parable": "https://en.wikipedia.org/wiki/The_Stanley_Parable",
  "Star Wars": "https://en.wikipedia.org/wiki/Star_Wars",
  "StarCraft": "https://en.wikipedia.org/wiki/StarCraft",
  "Stranger than Fiction": "https://en.wikipedia.org/wiki/Stranger_than_Fiction_(2006_film)",
  "Steven Universe": "https://en.wikipedia.org/wiki/Steven_Universe",
  "Strong Female Protagonist": "https://strongfemaleprotagonist.com/",
  "Suicide Squad": "https://en.wikipedia.org/wiki/Suicide_Squad_(film)",
  "Supreme Commander": "https://en.wikipedia.org/wiki/Supreme_Commander_(video_game)",
  "Sword Art Online": "https://en.wikipedia.org/wiki/Sword_Art_Online",
  "Tengen Toppa Gurren Lagann": "https://en.wikipedia.org/wiki/Gurren_Lagann",
  "Tokyo Ghoul": "https://en.wikipedia.org/wiki/Tokyo_Ghoul",
  "Touhou": "https://en.wikipedia.org/wiki/Touhou_Project",
  "Transformers": "https://en.wikipedia.org/wiki/Transformers",
  "Type-Moon": "https://en.wikipedia.org/wiki/Type-Moon",
  "Undertale": "https://en.wikipedia.org/wiki/Undertale",
  "Vampire: The Requiem": "https://en.wikipedia.org/wiki/Vampire:_The_Requiem",
  "Warcraft": "https://en.wikipedia.org/wiki/Warcraft",
  "Warframe": "https://en.wikipedia.org/wiki/Warframe",
  "Warhammer 40k": "https://en.wikipedia.org/wiki/Warhammer_40,000",
  "Warhammer 30k": "https://www.frontlinegaming.org/2015/11/13/the-horus-heresy-and-you-the-beginners-guide/",
  "Wheel of Time": "https://en.wikipedia.org/wiki/The_Wheel_of_Time",
  "Witcher": "https://en.wikipedia.org/wiki/The_Witcher",
  "Wonder Woman": "https://en.wikipedia.org/wiki/Wonder_Woman",
  "The World Ends With You": "https://en.wikipedia.org/wiki/The_World_Ends_with_You",
  "XCOM": "https://en.wikipedia.org/wiki/X-COM",
  "Young Justice": "https://en.wikipedia.org/wiki/Young_Justice_(TV_series)",
  "Yugioh": "https://en.wikipedia.org/wiki/Yu-Gi-Oh!",
}
